config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[index edit update destroy show] do
    member do
      put 'set_run'
      put 'clear_run'
      put 'set_admin'
      put 'clear_admin'
    end
  end
  resources :activities, only: %i[index show destroy] do
    collection do
      post 'sync_data'
    end
  end
  resources :challenges do
    member do
      post 'join'
      post 'quit'
      post 'sync_data'
      post 'sync_data_for_user'
      post 'remove_user'
      post 'set_target'
    end
  end
  resources :groups do
    member do
      post 'join'
      post 'quit'
      post 'remove_user'
    end
  end
  root to: 'pages#home'
  get 'connect_strava', to: 'pages#connect_strava'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_many :group_user_mappings, dependent: :destroy
  has_many :users, through: :group_user_mappings

  validates :name, presence: true

  scope :order_newest, lambda {
    order(id: :DESC)
  }
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  def index
    @q = Group.ransack(params[:q])
    @groups = @q.result(distinct: true).order(name: :ASC).paginate(page: params[:page])
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    unless current_user.is_admin
      flash[:alert] = 'Unauthorization'
      redirect_to root_path
      return
    end
    @group = Group.new
  end

  def edit
    unless current_user.is_admin
      flash[:alert] = 'Unauthorization'
      redirect_to root_path
      return
    end
    @group = Group.find(params[:id])
  end

  def create
    unless current_user.is_admin
      flash[:alert] = 'Unauthorization'
      redirect_to root_path
      return
    end
    @group = Group.new(group_params)

    if @group.save
      flash[:notice] = 'Create successfully'
      redirect_to groups_path
    else
      flash[:alert] = @group.errors.full_messages
      render :new
    end
  end

  def update
    unless current_user.is_admin
      flash[:alert] = 'Unauthorization'
      redirect_to root_path
      return
    end
    @group = Group.find(params[:id])

    if @group.update(group_params)
      flash[:notice] = 'Update successfully'
      redirect_to groups_path
    else
      flash[:alert] = @group.errors.full_messages
      render :edit
    end
  end

  def destroy
    unless current_user.is_admin
      flash[:alert] = 'Unauthorization'
      redirect_to root_path
      return
    end
    @group = Group.find(params[:id])
    @group.destroy
    flash[:notice] = 'Delete successfully'

    redirect_to groups_path
  end

  def join
    if current_user.team_run?
      flash[:alert] = 'Unauthorization'
      redirect_to root_path
      return
    end
    @group = Group.find(params[:id])
    GroupUserMapping.find_or_create_by(user: current_user, group: @group)
    flash[:notice] = 'Join successfully'

    redirect_to groups_path
  end

  def quit
    @group = Group.find(params[:id])
    GroupUserMapping.where(user: current_user, group: @group).destroy_all
    flash[:notice] = 'Quit successfully'

    redirect_to groups_path
  end

  def remove_user
    unless current_user.is_admin
      flash[:alert] = 'Unauthorization'
      redirect_to root_path
      return
    end
    @group = Group.find(params[:id])
    GroupUserMapping.where(user_id: params[:user_id], group: @group).destroy_all
    flash[:notice] = 'Remove successfully'

    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end
end

app/views/groups/_form.html.slim
.mb-3
= form_for group do |f|
  .form-group
    label Name
    = f.text_field :name, class: 'form-control', required: true
  .form-group
    label Users
    div
      - User.all.each do |user|
        .form-check
          = f.check_box :user_ids, {multiple: true, class: 'form-check-input'}, user.id, nil
          label.form-check-label.mr-3 = user.name
  = f.submit 'Submit', class: 'btn btn-primary'

app/views/groups/edit.html.slim
= render 'form', group: @group

app/views/groups/index.html.slim
ruby:
  user_group = current_user.groups.first

.d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.pb-2.mb-3.border-bottom
  h1.h2 Groups
  .btn-toolbar.mb-2.mb-md-0
    .btn-group.mr-2
      - if current_user.is_admin
        = link_to 'Add Group', new_group_path, class: 'btn btn-sm btn-outline-secondary'
= search_form_for @q, class: 'collapse border-bottom pb-2 mb-3', id: 'advance-search' do |f|
  = f.submit 'Submit', class: 'btn btn-primary'

= render 'shared/pagination', items: @groups
.table-responsive
  table.table.table-striped.table-bordered.table-sm
    thead
      tr
        th Name
        th Users
        th Count
        th Actions
    tbody
      - @groups.each do |group|
        tr
          td = group.name
          td = group.users.map(&:name).join(', ')
          td = group.users.count
          td
            - if user_group.present? && user_group.id == group.id
              = link_to 'Quit', quit_group_path(group), method: :post, class: 'btn btn-sm btn-danger mr-3 mb-3'
            - if current_user.team_run? && user_group.blank?
              = link_to 'Join', join_group_path(group), method: :post, class: 'btn btn-sm btn-info mr-3 mb-3'
            - if current_user.is_admin
              = link_to 'Edit', edit_group_path(group), class: 'btn btn-sm btn-info mr-3 mb-3'
              = link_to 'Delete', group_path(group), method: :delete, class: 'btn btn-sm btn-danger mb-3', data: {confirm: 'Are you sure?'}
= render 'shared/pagination', items: @groups

app/views/groups/new.html.slim
= render 'form', group: @group