config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[index edit update destroy show] do
    member do
      put 'set_run'
      put 'clear_run'
      put 'set_admin'
      put 'clear_admin'
    end
  end
  resources :activities, only: %i[index show destroy] do
    collection do
      post 'sync_data'
    end
  end
  resources :challenges do
    member do
      post 'join'
      post 'quit'
      post 'sync_data'
      post 'sync_data_for_user'
      post 'remove_user'
      post 'set_target'
    end
  end
  resources :groups do
    member do
      post 'join'
      post 'quit'
      post 'remove_user'
    end
  end
  root to: 'pages#home'
  get 'connect_strava', to: 'pages#connect_strava'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :activities, dependent: :destroy
  has_many :group_user_mappings, dependent: :destroy
  has_many :groups, through: :group_user_mappings
  has_many :challenge_user_mappings, dependent: :destroy
  has_many :challenges, through: :challenge_user_mappings

  scope :order_newest, lambda {
    order(id: :DESC)
  }
  scope :team_run, lambda {
    where(team: 'BNR')
  }

  def total_activities_in_challenge(challenge)
    result = activities.where(kind: 'Run')
                       .where(start_date_local: (challenge.start_date.beginning_of_day..challenge.end_date.end_of_day))
                       .order_newest
    result = result.select do |activity|
      activity.distance >= challenge.min_distance &&
        activity.pace <= challenge.max_pace &&
        activity.pace >= challenge.min_pace
    end
    if challenge.wo_limit
      result = result.select.with_index do |activity, index|
        pre = result[index - 1]
        if pre && pre.start_date_local.to_date == activity.start_date_local.to_date && pre.distance > activity.distance
          next
        end

        pos = result[index + 1]
        if pos && pos.start_date_local.to_date == activity.start_date_local.to_date && pos.distance > activity.distance
          next
        end

        true
      end
    end
    result
  end

  def update_point_in_challenge(challenge)
    activities = total_activities_in_challenge(challenge)
    mapping = ChallengeUserMapping.find_by(user: self, challenge: challenge)
    total_run_days = activities.map(&:start_date_local).map(&:to_date).uniq.count
    wo_5k_count = activities.select { |a| a.distance >= 5000 }.count
    wo_pace8_count = activities.select { |a| a.pace <= 5000 }.count
    wo_start_5am_count = activities.map(&:start_date_local).select do |date|
      date.hour < 5 || (date.hour == 5 && date.min <= 1)
    end.count
    hm_count = activities.select { |a| a.distance >= 21_100 && a.distance < 42_195 }.count
    fm_count = activities.select { |a| a.distance >= 42_195 }.count
    point = 0
    point += challenge.point_wo_day * total_run_days
    point += challenge.point_wo_5k * wo_5k_count
    point += challenge.point_wo_pace8 * wo_pace8_count
    point += challenge.point_wo_start_5am * wo_start_5am_count
    point += challenge.point_wo_21day * (total_run_days > 21 ? 1 : 0)
    point += challenge.point_wo_hm * hm_count
    point += challenge.point_wo_fm * fm_count
    mapping.update!(point: point)
    total_point = ChallengeUserMapping.where(user: self).pluck(:point).sum
    self.update(total_point: total_point)
  end

  def team_run?
    team == 'BNR'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).order_newest.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @q = @user.activities.ransack(params[:q])
    @activities = @q.result(distinct: true).order_newest.paginate(page: params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update!(params_user)
    flash[:notice] = 'Update successfully'

    redirect_to user_path(@user)
  end

  def destroy
    if current_user.is_admin
      @user = User.find(params[:id])
      @user.destroy
      flash[:notice] = 'Delete successfully'
    else
      flash[:alert] = 'Unauthorization'
    end

    redirect_to users_path
  end

  def set_admin
    if current_user.is_admin
      @user = User.find(params[:id])
      @user.update!(is_admin: true)
      flash[:notice] = 'Update successfully'
    else
      flash[:alert] = 'Unauthorization'
    end

    redirect_to users_path
  end

  def set_run
    if current_user.is_admin
      @user = User.find(params[:id])
      @user.update!(team: 'BNR')
      flash[:notice] = 'Update successfully'
    else
      flash[:alert] = 'Unauthorization'
    end

    redirect_to users_path
  end

  def clear_run
    if current_user.is_admin
      @user = User.find(params[:id])
      @user.update!(team: nil)
      flash[:notice] = 'Update successfully'
    else
      flash[:alert] = 'Unauthorization'
    end

    redirect_to users_path
  end

  def clear_admin
    if current_user.is_admin
      @user = User.find(params[:id])
      @user.update!(is_admin: false)
      flash[:notice] = 'Update successfully'
    else
      flash[:alert] = 'Unauthorization'
    end

    redirect_to users_path
  end

  private

  def params_user
    params.require(:user).permit(:name, :email, :password)
  end
end

app/views/users/edit.html.slim
.mb-3
= form_for @user do |f|
  .form-group
    label Name
    = f.text_field :name, class: 'form-control'
  .form-group
    label Email
    = f.email_field :email, class: 'form-control'
  .form-group
    label Password
    = f.password_field :password, class: 'form-control'
  = f.submit 'Submit', class: 'btn btn-primary'

app/views/users/index.html.slim
.d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.pb-2.mb-3.border-bottom
  h1.h2 Users
  .btn-toolbar.mb-2.mb-md-0
    .btn-group.mr-2
      button.btn.btn-sm.btn-outline-secondary data-toggle="collapse" data-target="#advance-search"
        | Advance Search
= search_form_for @q, class: 'collapse border-bottom pb-2 mb-3', id: 'advance-search' do |f|
  .form-group
    label Name or Email
    = f.search_field :name_or_email_cont, class: 'form-control'
  = f.submit 'Submit', class: 'btn btn-primary'

= render 'shared/pagination', items: @users
.table-responsive
  table.table.table-striped.table-bordered.table-sm
    thead
      tr
        th ID
        th Name
        th Email
        td Admin
        th Actions
    tbody
      - @users.each do |user|
        tr
          td = user.id
          td = user.name
          td = user.email
          td = user.is_admin ? 'Yes' : 'No'
          td
            = link_to 'Show', user_path(user), class: 'btn btn-sm btn-info mr-3 mb-3'
            - if current_user.is_admin && user.team_run?
              = link_to 'Clear Team', clear_run_user_path(user), method: :put, class: 'btn btn-sm btn-danger mr-3 mb-3', data: {confirm: 'Are you sure?'}
            - if !user.team_run?
              = link_to 'Set Team', set_run_user_path(user), method: :put, class: 'btn btn-sm btn-danger mr-3 mb-3', data: {confirm: 'Are you sure?'}
            - if current_user.is_admin && current_user.id != user.id
              = link_to 'Delete', user_path(user), method: :delete, class: 'btn btn-sm btn-danger mr-3 mb-3', data: {confirm: 'Are you sure?'}
              - if user.is_admin
                = link_to 'Clear Admin', clear_admin_user_path(user), method: :put, class: 'btn btn-sm btn-danger mr-3 mb-3', data: {confirm: 'Are you sure?'}
              - else
                = link_to 'Set Admin', set_admin_user_path(user), method: :put, class: 'btn btn-sm btn-danger mr-3 mb-3', data: {confirm: 'Are you sure?'}
            - if current_user.is_admin
              = link_to 'Edit', edit_user_path(user), class: 'nav-link', class: 'btn btn-sm btn-danger mr-3 mb-3'

= render 'shared/pagination', items: @users

app/views/users/show.html.slim
.d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.pb-2.mb-3.border-bottom
  h1.h2 = @user.name

.table-responsive
  table.table.table-striped.table-bordered.table-sm
    thead
      tr
        th Month
        th Distance
        th Time
    tbody
      - year = Time.current.year
      - (1..12).to_a.each do |month|
        - activities = @user.activities.kind_run.where(year: year, month: month)
        - if activities.present?
          tr
            td = month
            td = activities.map(&:distance).sum / 1000
            td = activities.map(&:moving_time).map(&:to_i).sum

= render 'shared/pagination', items: @activities
.table-responsive
  table.table.table-striped.table-bordered.table-sm
    thead
      tr
        th Type
        th Time
        th Distance
        th Pace
        - if current_user.is_admin
          th Action
    tbody
      - @activities.each do |activity|
        tr
          td = activity.kind
          td = activity.start_date_local.strftime('%Y-%m-%d %H:%M')
          td = activity.distance_format
          td = activity.pace_format
          - if current_user.is_admin
          td
            = link_to 'Delete', activity_path(activity), method: :delete, class: 'btn btn-sm btn-danger mr-3 mb-3', data: {confirm: 'Are you sure?'}
= render 'shared/pagination', items: @activities