config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[index edit update destroy show] do
    member do
      put 'set_run'
      put 'clear_run'
      put 'set_admin'
      put 'clear_admin'
    end
  end
  resources :activities, only: %i[index show destroy] do
    collection do
      post 'sync_data'
    end
  end
  resources :challenges do
    member do
      post 'join'
      post 'quit'
      post 'sync_data'
      post 'sync_data_for_user'
      post 'remove_user'
      post 'set_target'
    end
  end
  resources :groups do
    member do
      post 'join'
      post 'quit'
      post 'remove_user'
    end
  end
  root to: 'pages#home'
  get 'connect_strava', to: 'pages#connect_strava'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/challenge.rb
# frozen_string_literal: true

class Challenge < ApplicationRecord
  has_many :challenge_user_mappings, dependent: :destroy
  has_many :users, through: :challenge_user_mappings

  accepts_nested_attributes_for :challenge_user_mappings

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :min_distance, presence: true
  validates :min_pace, presence: true
  validates :max_pace, presence: true

  scope :order_newest, lambda {
    order(id: :DESC)
  }

  def self.current_challenge
    where('end_date >= ? AND start_date <= ?', Date.current, Date.current).first
  end
end

app/controllers/challenges_controller.rb
# frozen_string_literal: true

class ChallengesController < ApplicationController
  def index
    @q = Challenge.ransack(params[:q])
    @challenges = @q.result(distinct: true).order_newest.paginate(page: params[:page])
  end

  def show
    @challenge = Challenge.find(params[:id])
  end

  def new
    unless current_user.is_admin
      flash[:alert] = 'Unauthorization'
      redirect_to root_path
      return
    end
    @challenge = Challenge.new

  end

  def edit
    unless current_user.is_admin
      flash[:alert] = 'Unauthorization'
      redirect_to root_path
      return
    end
    @challenge = Challenge.find(params[:id])
  end

  def create
    unless current_user.is_admin
      flash[:alert] = 'Unauthorization'
      redirect_to root_path
      return
    end
    @challenge = Challenge.new(challenge_params)

    if @challenge.save
      @challenge.user_ids = User.team_run.pluck(:id)
      flash[:notice] = 'Create successfully'
      redirect_to challenge_path(@challenge)
    else
      flash[:alert] = @challenge.errors.full_messages
      render :new
    end
  end

  def update
    unless current_user.is_admin
      flash[:alert] = 'Unauthorization'
      redirect_to root_path
      return
    end
    @challenge = Challenge.find(params[:id])

    if @challenge.update(challenge_params)
      @challenge.user_ids = User.team_run.pluck(:id)
      flash[:notice] = 'Update successfully'
      redirect_to challenge_path(@challenge)
    else
      flash[:alert] = @challenge.errors.full_messages
      render :edit
    end
  end

  def destroy
    unless current_user.is_admin
      flash[:alert] = 'Unauthorization'
      redirect_to root_path
      return
    end
    @challenge = Challenge.find(params[:id])
    @challenge.destroy
    flash[:notice] = 'Delete successfully'

    redirect_to challenges_path
  end

  def sync_data
    @challenge = Challenge.find(params[:id])
    @challenge.users.each do |user|
      StravaApi.sync_data(user)
      user.update_point_in_challenge(@challenge)
    end
    flash[:notice] = 'Sync successfully'

    redirect_to challenge_path(@challenge)
  end

  def sync_data_for_user
    @challenge = Challenge.find(params[:id])
    @user = User.find(params[:user_id])
    StravaApi.sync_data(@user)
    @user.update_point_in_challenge(@challenge)

    flash[:notice] = 'Sync successfully'

    redirect_to challenge_path(@challenge)
  end

  def set_target
    @challenge = Challenge.find(params[:id])
    @user = User.find(params[:user_id])
    mapping = ChallengeUserMapping.find_by(user: @user, challenge: @challenge)
    mapping.update!(target: params[:challenge_target])

    flash[:notice] = 'Update successfully'

    redirect_to challenge_path(@challenge)
  end

  def join
    unless current_user.team_run?
      flash[:alert] = 'Unauthorization'
      redirect_to root_path
      return
    end
    @challenge = Challenge.find(params[:id])
    ChallengeUserMapping.find_or_create_by(user: current_user, challenge: @challenge)
    flash[:notice] = 'Join successfully'

    redirect_to challenge_path(@challenge)
  end

  def quit
    @challenge = Challenge.find(params[:id])
    ChallengeUserMapping.where(user: current_user, challenge: @challenge).destroy_all
    flash[:notice] = 'Quit successfully'

    redirect_to challenge_path(@challenge)
  end

  def remove_user
    unless current_user.is_admin
      flash[:alert] = 'Unauthorization'
      redirect_to root_path
      return
    end
    @challenge = Challenge.find(params[:id])
    ChallengeUserMapping.where(user_id: params[:user_id], challenge: @challenge).destroy_all
    flash[:notice] = 'Remove successfully'

    redirect_to challenge_path(@challenge)
  end

  private

  def challenge_params
    params.require(:challenge).permit(
      :name,
      :start_date,
      :end_date,
      :min_distance,
      :min_pace,
      :max_pace,
      :point_wo_day,
      :point_wo_5k,
      :point_wo_pace8,
      :point_wo_start_5am,
      :point_wo_21day,
      :point_wo_hm,
      :point_wo_fm,
      :point_wo_finish_21day
    )
  end
end

app/views/challenges/_form.html.slim
.mb-3
= form_for challenge do |f|
  .form-group
    label Name
    = f.text_field :name, class: 'form-control', required: true
  .form-group
    label Start Date
    = f.date_field :start_date, class: 'form-control', required: true
  .form-group
    label End Date
    = f.date_field :end_date, class: 'form-control', required: true
  .form-group
    label Min Distance (metter)
    = f.number_field :min_distance, class: 'form-control', required: true
  .form-group
    label Min Pace (min/km)
    = f.number_field :min_pace, class: 'form-control', required: true
  .form-group
    label Max Pace (min/km)
    = f.number_field :max_pace, class: 'form-control', required: true
  .form-group
    label WO Day Point
    = f.number_field :point_wo_day, class: 'form-control', required: true
  .form-group
    label WO 5K Point
    = f.number_field :point_wo_5k, class: 'form-control', required: true
  .form-group
    label WO Pace8 Point
    = f.number_field :point_wo_pace8, class: 'form-control', required: true
  .form-group
    label WO Start 5AM Point
    = f.number_field :point_wo_start_5am, class: 'form-control', required: true
  .form-group
    label Run 21 days Point
    = f.number_field :point_wo_21day, class: 'form-control', required: true
  .form-group
    label WO Hafl Marathon Point
    = f.number_field :point_wo_hm, class: 'form-control', required: true
  .form-group
    label WO Full Marathon Point
    = f.number_field :point_wo_fm, class: 'form-control', required: true
  .form-group
    label Finish 21 days Point
    = f.number_field :point_wo_finish_21day, class: 'form-control', required: true
  = f.submit 'Submit', class: 'btn btn-primary'

app/views/challenges/edit.html.slim
= render 'form', challenge: @challenge

app/views/challenges/index.html.slim
.d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.pb-2.mb-3.border-bottom
  h1.h2 Challenges
  .btn-toolbar.mb-2.mb-md-0
    .btn-group.mr-2
      - if current_user.is_admin
        = link_to 'Add Challenge', new_challenge_path, class: 'btn btn-sm btn-outline-secondary'
= search_form_for @q, class: 'collapse border-bottom pb-2 mb-3', id: 'advance-search' do |f|
  = f.submit 'Submit', class: 'btn btn-primary'

= render 'shared/pagination', items: @challenges
.table-responsive
  table.table.table-striped.table-bordered.table-sm
    thead
      tr
        th Name
        th Time
        th Detail
        th Users
        th Actions
    tbody
      - @challenges.each do |challenge|
        tr
          td = challenge.name
          td = "#{challenge.start_date} - #{challenge.end_date}"
          td
            p = "Min distance: #{challenge.min_distance} m"
            p = "Min pace: #{challenge.min_pace}"
            p = "Max pace: #{challenge.max_pace}"
          td = challenge.users.count
          td
            = link_to 'Show', challenge_path(challenge), class: 'btn btn-sm btn-info mr-3 mb-3'
            - if current_user.team_run? && !ChallengeUserMapping.exists?(challenge: challenge, user: current_user)
              = link_to 'Join', join_challenge_path(challenge), method: :post, class: 'btn btn-sm btn-info mr-3 mb-3'
            - if current_user.is_admin
              = link_to 'Delete', challenge_path(challenge), method: :delete, class: 'btn btn-sm btn-danger mb-3', data: {confirm: 'Are you sure?'}
= render 'shared/pagination', items: @challenges

app/views/challenges/new.html.slim
= render 'form', challenge: @challenge

app/views/challenges/show.html.slim
ruby:
  mapping = ChallengeUserMapping.find_by(user: current_user, challenge: @challenge)
.d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.pb-2.mb-3.border-bottom
  h1.h2 Challenge
  .btn-toolbar.mb-2.mb-md-0
    .btn-group.mr-2
      = link_to 'Sync Data', sync_data_challenge_path(@challenge), method: :post, class: 'btn btn-sm btn-outline-secondary'
      - if mapping.blank?
        = link_to 'Join', join_challenge_path(@challenge), method: :post, class: 'btn btn-sm btn-outline-secondary'
      button.btn.btn-sm.btn-outline-secondary data-toggle="collapse" data-target="#set-target"
        | Set Target
      - if current_user.is_admin
        = link_to 'Edit Challenge', edit_challenge_path(@challenge), class: 'btn btn-sm btn-outline-secondary'


= form_tag set_target_challenge_path(@challenge, user_id: current_user.id), method: :post, class: 'collapse border-bottom pb-2 mb-3', id: 'set-target' do |f|
  .form-group
    label Target
    = number_field_tag :challenge_target, nil, class: 'form-control'
  = submit_tag 'Submit', class: 'btn btn-primary'

.table-responsive.mb-3
  table.table.table-striped.table-bordered.table-sm
    thead
      th Min Road(M)
      th Start
      th End
      th Min Pace(Min/Km)
      th Max Pace(Min/Km)
    tbody
      td = @challenge.min_distance
      td = @challenge.start_date.to_date
      td = @challenge.end_date.to_date
      td = @challenge.min_pace
      td = @challenge.max_pace
.table-responsive.mb-3
  table.table.table-striped.table-bordered.table-sm
    thead
      th Index
      th style="min-width: 150px" User
      th style="min-width: 50px" Target
      th style="min-width: 50px" Total
      th style="min-width: 50px" Point
      th style="min-width: 200px" Week 1
      th style="min-width: 200px" Week 2
      th style="min-width: 200px" Week 3
      th style="min-width: 200px" Week 4
      th style="min-width: 200px" Week 5
      th Actions
    tbody
      - @challenge.challenge_user_mappings.order('total desc').preload(:user).each.with_index(1) do |mapping, index|
        - user = mapping.user
        - activities = user.total_activities_in_challenge(@challenge)
        - w1_wo = activities.select {|a| a.week == 1}
        - w2_wo = activities.select {|a| a.week == 2}
        - w3_wo = activities.select {|a| a.week == 3}
        - w4_wo = activities.select {|a| a.week == 4}
        - w5_wo = activities.select {|a| a.week == 5}
        - total = (activities.map(&:distance).sum.to_f / 1000).floor(2)
        tr
          td = index
          td = user.name
          td = mapping.target
          td = total
          td = mapping.point
          td
            - w1_wo.each do |activity|
              p = activity.brief_information
          td
            - w2_wo.each do |activity|
              p = activity.brief_information
          td
            - w3_wo.each do |activity|
              p = activity.brief_information
          td
            - w4_wo.each do |activity|
              p = activity.brief_information
          td
            - w5_wo.each do |activity|
              p = activity.brief_information
          td
            = link_to 'Sync', sync_data_for_user_challenge_path(@challenge, user_id: user.id), method: :post, class: 'btn btn-sm btn-info mr-3 mb-3', remote: true
            - if current_user.is_admin
              = link_to 'Delete', remove_user_challenge_path(@challenge, user_id: user.id), method: :post, class: 'btn btn-sm btn-danger mr-3 mb-3', data: {confirm: 'Are you sure?'}
div
  = link_to 'Back', challenges_path, class: 'btn btn-lg btn-info mr-3'