config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[index edit update destroy show] do
    member do
      put 'set_run'
      put 'clear_run'
      put 'set_admin'
      put 'clear_admin'
    end
  end
  resources :activities, only: %i[index show destroy] do
    collection do
      post 'sync_data'
    end
  end
  resources :challenges do
    member do
      post 'join'
      post 'quit'
      post 'sync_data'
      post 'sync_data_for_user'
      post 'remove_user'
      post 'set_target'
    end
  end
  resources :groups do
    member do
      post 'join'
      post 'quit'
      post 'remove_user'
    end
  end
  root to: 'pages#home'
  get 'connect_strava', to: 'pages#connect_strava'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.slim
ruby:
  current_challenge = Challenge.current_challenge

nav.navbar.navbar-expand-sm.bg-dark.navbar-dark.sticky-top
  button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item
        a.nav-link href="/"
          | Home
      li.nav-item
        = link_to activities_path, class: 'nav-link' do
          span data-feather="activity"
          | Activities
      - if current_challenge.present?
        li.nav-item
          = link_to challenge_path(current_challenge), class: 'nav-link' do
            span data-feather="activity"
            | Current Challenge
      li.nav-item
        = link_to challenges_path, class: 'nav-link' do
          span data-feather="star"
          | Challenges
      li.nav-item
        = link_to users_path, class: 'nav-link' do
          span data-feather="users"
          | Users
      li.nav-item
        = link_to edit_user_path(current_user), class: 'nav-link' do
          span data-feather="database"
          | Change Password
      li.nav-item
        = link_to destroy_user_session_path, class: 'nav-link', method: :delete do
          span data-feather="log-out"
          | Logout

app/views/layouts/application.html.slim
doctype html
html
  head
    title Strava Statistic
    = csrf_meta_tags
    = csp_meta_tag
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    -if user_signed_in?
      .container-fluid
        = render 'layouts/header'
        - if notice
          .alert.alert-warning.alert-dismissible.fade.show.mt-3 role="alert"
            = notice
            button.close aria-label="Close" data-dismiss="alert" type="button"
              span aria-hidden="true"  &times;
        - if alert
          .alert.alert-alert.alert-dismissible.fade.show.mt-3 role="alert"
            = alert
            button.close aria-label="Close" data-dismiss="alert" type="button"
              span aria-hidden="true"  &times
        = yield
        .mt-5
    - else
      .container
        = yield